import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BookingProvider } from "./contexts/BookingProvider";
import { Banner } from "./ui/banner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="scroll-smooth">
            <body className={inter.className}>
                {/* <BookingProvider> */}
                <Banner
                    title="Demo version"
                    content="Cette application est à but démonstratif uniquement ! Vous l'aimez ? Donnez lui une étoile sur github!"
                    link={{ url: "https://github.com/bzfvrto", text: "C'est parti" }}
                />
                {children}
                {/* </BookingProvider> */}
            </body>
        </html>
    );
}
